### ISSUE TITLE
Winner detection

### ISSUE THREAD

**Issue by phelios** [michael-robbins/emojirades-plusplus#8]
Detect the winner from emojirade registry and award the winner with a ++
maybe print the leaderboard at the same time.

**Comment by michael-robbins** [comment]
Once #7 is done we would have a state object that contains the current rade, it would then be trivial to monitor user chat in the selected emojirade channel and check for matches and handle them appropriately

Hell, we could even try adding in something that checks for misspellings/close-ness and put in reactions/etc! That would be cool!

**Comment by michael-robbins** [comment]
Game state implementation now includes this feature. We can tweak how we like later.

Currently it lowercases the current emojirade and the current guess (the entire text of the event), and if they are equal awards the win.

Maybe we can look to do a string 'similarity' comparison and award on >0.95 confidence/etc, might handle small misspellings of the 'rade...

**Comment by michael-robbins** [comment]
I've added in basic winner detection here: https://github.com/michael-robbins/emojirades-plusplus/blob/master/plusplusbot/gamestate.py#L110

**Comment by michael-robbins** [comment]
@phelios how do we want to approach this now we have a framework around being able to detect user text and react accordingly to it?

Some things that come to mind:
1. Scanning various parts of the text instead of a direct entire string match? (regex?)
2. stripping out various '!' '?' etc, but will this break the logic of the 'rade?
3. similarity comparison? is there an easy python library we can insert to do this for us?

**Comment by michael-robbins** [comment]
I've adjusted the logic in #29 to perform an 'emojirade in guess' string-in-string match instead.
